In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import sys
print(sys.executable)

C:\Users\ahn18\Anaconda3\python.exe

In [3]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('./data2/ybigta_sdss_train.csv',)
test_data = pd.read_csv('./data2/ybigta_sdss_test.csv',)
data.head()

,id,type,fiberID,psfMag_u,psfMag_g,psfMag_r,psfMag_i,psfMag_z,fiberMag_u,fiberMag_g,...,petroMag_u,petroMag_g,petroMag_r,petroMag_i,petroMag_z,modelMag_u,modelMag_g,modelMag_r,modelMag_i,modelMag_z
0,415567,QSO,106,19.20636,18.83202,18.79017,18.36788,18.32136,19.33958,18.72630,...,18.06469,17.18273,16.74307,16.39772,16.28030,17.60089,16.82960,16.46197,16.09962,16.01179
1,733874,QSO,492,18.85419,18.60349,18.48284,18.36558,18.41101,19.17574,18.90761,...,18.90764,18.64323,18.49622,18.38058,18.47802,18.84907,18.59603,18.46161,18.34665,18.40146
2,1009150,QSO,388,19.81733,18.67198,18.46566,18.33873,18.31073,20.17311,19.00520,...,19.85916,18.70682,18.51968,18.37718,18.37598,19.81720,18.66244,18.45800,18.32918,18.31313
3,803041,QSO,531,21.77330,20.19641,20.08064,20.11380,19.83673,22.16908,20.56249,...,21.38145,20.22594,20.13081,20.15601,20.04247,21.76902,20.18548,20.07931,20.10771,19.85110
4,432241,QSO,180,22.53572,20.07427,19.23110,18.94043,18.65541,22.82620,20.41057,...,22.09349,20.14050,19.25699,18.98682,18.63438,22.58755,20.07051,19.21149,18.90649,18.63881

In [5]:
orb_type = [
    "GALAXY",
    "QSO",
    "REDDEN_STD",
    "ROSAT_D",
    "SERENDIPITY_BLUE",
    "SERENDIPITY_DISTANT",
    "SERENDIPITY_FIRST",
    "SERENDIPITY_MANUAL",
    "SERENDIPITY_RED",
    "SKY",
    "SPECTROPHOTO_STD",
    "STAR_BHB",
    "STAR_BROWN_DWARF",
    "STAR_CARBON",
    "STAR_CATY_VAR",
    "STAR_PN",
    "STAR_RED_DWARF",
    "STAR_SUB_DWARF",
    "STAR_WHITE_DWARF"
]
def sampling(df, orb_type): #df : 데이터프레임, orb_type : 천체타입 리스트
    copy_train = df.copy()
    for t in orb_type:
        print("현재 type : ", t)
        insert_row = int(input("랜덤샘플링으로 추가할 개수를 입력하세요 : "))
        print("\n")
        temp = df[df["type"]==t].sample(n = insert_row, replace=True)  #t는 tpye의 종류, replace = True 옵션을 줘야 개수가 더 많아도 샘플링 가능
        copy_train = pd.concat([copy_train, temp], axis = 0) #row로 붙여넣기
    return copy_train

In [6]:
count = data.groupby("type").size().reset_index(name = "count")
count

                   type  count
0                GALAXY  34000
1                   QSO  42500
2            REDDEN_STD  13052
3               ROSAT_D   5559
4      SERENDIPITY_BLUE  19439
5   SERENDIPITY_DISTANT   4163
6     SERENDIPITY_FIRST   5718
7    SERENDIPITY_MANUAL     46
8       SERENDIPITY_RED   1312
9                   SKY    170
10     SPECTROPHOTO_STD  13073
11             STAR_BHB  12069
12     STAR_BROWN_DWARF    220
13          STAR_CARBON   2875
14        STAR_CATY_VAR   5808
15              STAR_PN     12
16       STAR_RED_DWARF   9040
17       STAR_SUB_DWARF    977
18     STAR_WHITE_DWARF   1932

In [7]:
data = sampling(data, ["STAR_PN", "SERENDIPITY_MANUAL", "SKY", "STAR_BROWN_DWARF"])

현재 type :  STAR_PN
랜덤샘플링으로 추가할 개수를 입력하세요 : 100


현재 type :  SERENDIPITY_MANUAL
랜덤샘플링으로 추가할 개수를 입력하세요 : 300


현재 type :  SKY
랜덤샘플링으로 추가할 개수를 입력하세요 : 800


현재 type :  STAR_BROWN_DWARF
랜덤샘플링으로 추가할 개수를 입력하세요 : 900

In [8]:
test_data.head(5)

,id,fiberID,psfMag_u,psfMag_g,psfMag_r,psfMag_i,psfMag_z,fiberMag_u,fiberMag_g,fiberMag_r,...,petroMag_u,petroMag_g,petroMag_r,petroMag_i,petroMag_z,modelMag_u,modelMag_g,modelMag_r,modelMag_i,modelMag_z
0,70379,182,18.81052,18.32911,17.90038,17.70225,17.65288,19.15704,18.62413,18.25862,...,18.85941,18.33458,17.93811,17.74766,17.68350,18.80268,18.32140,17.89795,17.69311,17.66096
1,863365,207,22.99911,21.23738,19.89757,19.26474,19.88944,23.23582,21.56254,20.21074,...,22.60821,21.30784,19.90107,19.31741,19.59066,23.08329,21.22320,19.89089,19.25760,19.78871
2,40381,496,18.91604,18.69714,18.59921,18.68769,18.63109,19.21263,18.99961,18.91325,...,18.92110,18.72866,18.63251,18.71346,18.47264,18.91443,18.68466,18.58225,18.67094,18.58222
3,1322598,441,19.22888,18.64079,18.68171,18.52602,18.22359,19.02119,18.28669,18.20239,...,17.71678,16.83449,16.67583,16.49454,16.33526,17.69108,16.90666,16.79139,16.57578,16.47379
4,1201659,320,19.57746,19.57045,19.23320,19.02790,18.62246,19.87532,19.80541,19.32947,...,19.15427,18.84896,18.01861,17.66363,17.29827,18.74826,18.57701,17.93407,17.64736,17.20101

In [9]:
len(data['type'].unique())

19

In [10]:
X = data[data.columns[2:]]
y= data['type']

In [8]:
# import xgboost as xgb
# xgb_model = xgb.XGBClassifier(n_estimators=2000,
#                         n_jobs=4,
#                         max_depth=15,
#                         learning_rate=0.05,
#                         gamma = 0.02,
#                         subsample = 0.9,
#                         colsample_bytree=0.9,
#                         missing=-999,
#                         tree_method='gpu_hist')

In [9]:
# xgb_model.fit(X, y)

In [11]:
from lightgbm import LGBMClassifier
lgbm_model = LGBMClassifier(boosting_type='gbdt', objective='binary', num_leaves=128,
                                learning_rate=0.005, n_estimators=2000, max_depth=30,
                                bagging_fraction=0.9, feature_fraction=0.9, reg_lambda=0.2)

In [12]:
lgbm_model.fit(X,y)

LGBMClassifier(bagging_fraction=0.9, boosting_type='gbdt', class_weight=None,
               colsample_bytree=1.0, feature_fraction=0.9,
               importance_type='split', learning_rate=0.005, max_depth=30,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=2000, n_jobs=-1, num_leaves=128, objective='binary',
               random_state=None, reg_alpha=0.0, reg_lambda=0.2, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [13]:
id_for_index = test_data['id']
test = test_data[test_data.columns[1:]]

In [14]:
predictions = lgbm_model.predict_proba(X = test)

In [15]:
result = pd.DataFrame(data=predictions, index=id_for_index, columns=lgbm_model.classes_)
result.head()
len(result)

30338

In [16]:
sample = pd.read_csv("./data2/ybigta_sdss_sample_submission.csv")
col_order = sample.columns[1:]

In [17]:
result = result[col_order]
result.head()

,STAR_WHITE_DWARF,STAR_CATY_VAR,STAR_BROWN_DWARF,SERENDIPITY_RED,REDDEN_STD,STAR_BHB,GALAXY,SERENDIPITY_DISTANT,QSO,SKY,STAR_RED_DWARF,ROSAT_D,STAR_PN,SERENDIPITY_FIRST,STAR_CARBON,SPECTROPHOTO_STD,STAR_SUB_DWARF,SERENDIPITY_MANUAL,SERENDIPITY_BLUE
id,,,,,,,,,,,,,,,,,,,
70379,0.001314,0.000122,0.000017,0.000024,0.005791,0.004762,0.000850,0.000370,0.968229,0.000015,0.000141,0.016822,0.000002,0.000131,0.000067,0.000195,0.000015,0.000007,0.001126
863365,0.000019,0.000042,0.000011,0.000012,0.000096,0.000086,0.000725,0.000124,0.977957,0.000011,0.000066,0.011395,0.000001,0.009105,0.000083,0.000090,0.000008,0.000005,0.000163
40381,0.000564,0.000386,0.000008,0.000010,0.000096,0.001640,0.000396,0.000427,0.990756,0.000007,0.000065,0.003977,0.000001,0.000058,0.000025,0.000090,0.000007,0.000003,0.001483
1322598,0.000295,0.000175,0.000031,0.000041,0.000417,0.002143,0.068366,0.000454,0.923021,0.000027,0.000254,0.003372,0.000004,0.000236,0.000094,0.000349,0.000027,0.000012,0.000684
1201659,0.000208,0.000119,0.000016,0.000021,0.000190,0.000331,0.002917,0.000265,0.969176,0.000014,0.000129,0.025013,0.000002,0.000996,0.000044,0.000178,0.000014,0.000007,0.000361

In [18]:
result.to_csv('./result/new_sample2_lgbm_clf.csv', sep=',')